### ISSUE TITLE
missing functions in client-go

### ISSUE THREAD

**Issue by lxm** [kubevirt/api#2]
there are many functions missing
like VirtualMachine->Start()

**Comment by rmohr** [comment]
Hi,

due to how client-gen work, we can not inject subresource code properly into the clients right now. That is why the subresources are missing for now. Let me see if we can improve that on the client-gen side.

**Comment by rmohr** [comment]
Created a feature request: https://github.com/kubernetes/code-generator/issues/138

**Comment by drssdinblck** [comment]
/remove-lifecycle stale

This would be an important feature for me as well. Although a current work around is to set the virtual machine `running: true`.
